"""
Django settings for allaboutfilm project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-b!0hz3k^@5-9qpp447$v@k@j^ec9bz(m*(4p^s+nssy^+$n6fd',
)

# SECURITY WARNING: don't run with debug turned on in production!
# With DEBUG on, Django answers a bad URL with its technical error page, which
# lists the whole URL configuration, the settings and a traceback. So DEBUG is
# off by default: bad links get templates/404.html and crashes get 500.html,
# and none of that internal detail is ever exposed.
# Turn it back on only while developing, to get tracebacks:
#     DJANGO_DEBUG=True python manage.py runserver
DEBUG = os.environ.get('DJANGO_DEBUG', 'False').strip().lower() in ('true', '1', 'yes')

# Hosts allowed to serve the site. Locally the defaults are enough; in
# production set DJANGO_ALLOWED_HOSTS to a comma-separated list that includes the
# deployed domain, e.g. "nckvmk.pythonanywhere.com".
ALLOWED_HOSTS = [h.strip() for h in os.environ.get(
    'DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1,[::1]'
).split(',') if h.strip()]

# PythonAnywhere (like most hosts) terminates HTTPS at a proxy and forwards the
# request to Django over plain HTTP, with the real scheme in X-Forwarded-Proto.
# Trust that header so request.is_secure() is correct.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# The browser sends "Origin: https://<domain>" on every POST. Without a matching
# https:// entry here, Django rejects the request as a bad origin (403 CSRF) — so
# login and all forms break on the live site. Derived from the deployed host(s);
# empty locally (plain http, same-origin, so no check is needed).
CSRF_TRUSTED_ORIGINS = [
    f'https://{host}' for host in ALLOWED_HOSTS
    if host not in ('localhost', '127.0.0.1', '[::1]')
]


# Application definition

INSTALLED_APPS = [
    'home',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms',
    'crispy_bootstrap5',
]

# django-crispy-forms: render forms with the Bootstrap 5 template pack
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'home.middleware.SuspendedUserMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'allaboutfilm.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'home.context_processors.cart_count',
                'home.context_processors.wishlist_codes',
                'home.context_processors.is_staff_member',
            ],
        },
    },
]

WSGI_APPLICATION = 'allaboutfilm.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# `python manage.py collectstatic` gathers every static file (ours + Django
# admin's) into this one folder, which the production web server points at.
# Not used by the local dev server.
STATIC_ROOT = BASE_DIR / "staticfiles"

# Media files (user-uploaded content, e.g. product images)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / "media"

# Use our custom user model instead of the default auth.User.
# Must be set before the very first migration.
AUTH_USER_MODEL = 'home.User'

# Auth flow redirects (the account page doubles as the login page).
LOGIN_URL = 'account'
LOGIN_REDIRECT_URL = 'account'

# Default primary key type for models that don't define their own.
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
