# Generated by Django 6.0.6 on 2026-07-10 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lens',
            options={'verbose_name_plural': 'Lenses'},
        ),
    ]
