# Generated by Django 6.0.6 on 2026-07-11 18:05

from django.db import migrations


def seed(apps, schema_editor):
    ShippingMethod = apps.get_model('home', 'ShippingMethod')
    methods = [
        ('Elta Standard - Greece', '5.00', 1),
        ('Elta Standard - Europe', '14.50', 2),
        ('DHL Express - Europe', '20.00', 3),
        ('Elta Standard - Outside EU', '25.00', 4),
        ('DHL Express - Outside EU', '35.00', 5),
    ]
    for name, price, position in methods:
        ShippingMethod.objects.get_or_create(
            name=name, defaults={'price': price, 'position': position}
        )


def unseed(apps, schema_editor):
    ShippingMethod = apps.get_model('home', 'ShippingMethod')
    ShippingMethod.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_shippingmethod'),
    ]

    operations = [
        migrations.RunPython(seed, unseed),
    ]
